# Generated by Django 4.1.3 on 2022-11-29 09:18

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_adminnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_image1',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_image2',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_image3',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
